repos:

# Other file formatting, plus common Git mistakes & text file standardization:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files # Don't accidentally commit giant files.
  - id: check-merge-conflict    # Watch for lingering merge markers.
  - id: check-yaml              # Validate all YAML files.
  - id: check-case-conflict     # Avoid case sensitivity in file names.
  - id: debug-statements        # Watch for lingering debugger calls.
  - id: end-of-file-fixer       # Ensure there's a newline at EOF.
  - id: mixed-line-ending       # Only newlines, no line-feeds.
  - id: trailing-whitespace     # Remove trailing whitespace.
  - id: name-tests-test         # Follow PyTest naming convention.

# Make sure import statements are sorted uniformly.
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

# Check for PEP8 non-compliance, code complexity, style, errors, etc:
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args:
      # make line length compatible with black
      - "--max-line-length=119"
      - "--max-complexity=18"
      - "--select=B,C,E,F,W,T4,B9"
    additional_dependencies:
      - flake8-docstrings
      - flake8-colors
      - pydocstyle
      - flake8-builtins
      - mccabe
      - pep8-naming
      - pycodestyle
      - pyflakes
      - flake8-use-fstring

# Format the code
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args:
        - --line-length=119
        - --exclude="""\.git |
          \.__pycache__|
          \.mypy_cache|
          \.tox|
          \.venv|
          _build|
          \.vscode|
          \.pytest_cache|
          data|
          notebooks|
          references|
          reports|
          sql_queries|
          dist"""

    language_version: python3.9
