name: gsod
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.9.0
  - pandas
  - numpy
  - scikit-learn
  - jupyterlab
  - seaborn
  - matplotlib
  - altair
  - black
  - isort
  - mypy
  - flake8
  - pytest
  - pre-commit
  - geopandas
  - scipy
  - basemap
  - nodejs

  - pip:
    - --editable .
